### ISSUE TITLE
getaddrinfo ENOTFOUND api.magnetcustomer.com | The connection cannot be established

### ISSUE THREAD

**Issue by ricardoisus** [magnetcustomer/n8n-nodes-magnetcustomer#1]
Contexto: Não consigo fazer qualquer requisição com o módulo da MagnetCustomer, sempre aparece o erro ENOTFOUND.

Informações:

![tela-n8n](https://github.com/user-attachments/assets/756d7bf4-3efc-4952-83cb-2a8fdaea8b59)

{
  "errorMessage": "Internal error",
  "errorDescription": "getaddrinfo ENOTFOUND api.magnetcustomer.com",
  "errorDetails": {
    "rawErrorMessage": [
      "The connection cannot be established, this usually occurs due to an incorrect host (domain) value",
      "The connection cannot be established, this usually occurs due to an incorrect host (domain) value"
    ],
    "httpCode": "ENOTFOUND"
  },
  "n8nDetails": {
    "nodeName": "MagnetCustomer",
    "nodeType": "@magnetcustomer/n8n-nodes-magnetcustomer.magnetCustomer",
    "nodeVersion": 1,
    "resource": "person",
    "operation": "create",
    "time": "18/10/2024, 15:26:01",
    "n8nVersion": "1.54.0 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "NodeApiError: The connection cannot be established, this usually occurs due to an incorrect host (domain) value",
      "    at Object.<anonymous> (/home/node/.n8n/nodes/node_modules/@magnetcustomer/n8n-nodes-magnetcustomer/nodes/MagnetCustomer/GenericFunctions.ts:93:9)",
      "    at Generator.throw (<anonymous>)",
      "    at rejected (/home/node/.n8n/nodes/node_modules/@magnetcustomer/n8n-nodes-magnetcustomer/dist/nodes/MagnetCustomer/GenericFunctions.js:6:65)",
      "    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
    ]
  }
}

Conexão:
![conexão](https://github.com/user-attachments/assets/c153cd6a-06e6-4dfb-baf3-7d1bb6d7cddb)

**Comment by ricardoisus** [comment]
No campo de "Subdomain Platform URL" ao invés de utilizar url completa, coloquei somente o primeiro termo da url e funcionou corretamente.

Exemplo: ao invés de preencher o campo com "subdomain.mydomain.com", preenchi apenas com "subdomain". (sem aspas) 

Além disso, atualizei para versão 1.2.0 do node.

Funcionando corretamente (y)

**Comment by marcelosantanajr** [comment]
Hi! This error occurs when the subdomain is not configured correctly in the credentials.

**How to fix:**
1. Go to your n8n credentials for Magnet Customer
2. In the **Subdomain Platform URL** field, enter only your subdomain (e.g., mycompany)
3. The full URL is built automatically: https://mycompany.platform-api.magnetcustomer.com/api

**Important:** With version 2.0.0, this node requires MagnetCustomer platform V2.

Closing as this is a configuration issue.
